/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The Botpress conversation ID to assign to the trace
   */
  conversationId: string;
  /**
   * Role of sender ("user" | "assistant")
   */
  role: string;
  /**
   * Content of the message (e.g. "Hello, how are you?")
   */
  content: string;
  /**
   * JSON string for metadata of the message
   */
  metadata?: string;
}
