/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * Name of the track event (e.g. "Clicked on Purchase Button")
   */
  name: string;
  /**
   * The Botpress conversation ID to assign to the track event
   */
  traceId: string;
  /**
   * Additional properties of the track event (MUST be a JSON string)
   */
  properties?: string;
}
