/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The user ID to assign the track event to (use {{event.userId}})
   */
  userId?: string;
  /**
   * Name of the track event (e.g. "Clicked on Purchase Button")
   */
  name: string;
  /**
   * The Botpress conversation ID to assign to the track event (use {{event.conversationId}})
   */
  traceId?: string;
  /**
   * Additional properties of the track event (MUST be a JSON string)
   */
  properties?: string;
}
