/* tslint:disable */
// This file is generated
// Do not edit this file
import * as identifyUser from "./identifyUser/index";
export * as identifyUser from "./identifyUser/index";
import * as logTrackEvent from "./logTrackEvent/index";
export * as logTrackEvent from "./logTrackEvent/index";
import * as logMessageMetadata from "./logMessageMetadata/index";
export * as logMessageMetadata from "./logMessageMetadata/index";

export type Actions = {
  identifyUser: identifyUser.ActionIdentifyUser;
  logTrackEvent: logTrackEvent.ActionLogTrackEvent;
  logMessageMetadata: logMessageMetadata.ActionLogMessageMetadata;
}
