/* tslint:disable */
// This file is generated
// Do not edit this file
import * as captureTrackEvent from "./captureTrackEvent/index";
export * as captureTrackEvent from "./captureTrackEvent/index";
import * as identifyUser from "./identifyUser/index";
export * as identifyUser from "./identifyUser/index";

export type Actions = {
  captureTrackEvent: captureTrackEvent.ActionCaptureTrackEvent;
  identifyUser: identifyUser.ActionIdentifyUser;
}
