/* tslint:disable */
// This file is generated
// Do not edit this file
import * as captureTrackEvent from "./captureTrackEvent/index";
export * as captureTrackEvent from "./captureTrackEvent/index";
import * as captureTraceData from "./captureTraceData/index";
export * as captureTraceData from "./captureTraceData/index";
import * as openTrace from "./openTrace/index";
export * as openTrace from "./openTrace/index";

export type Actions = {
  captureTrackEvent: captureTrackEvent.ActionCaptureTrackEvent;
  captureTraceData: captureTraceData.ActionCaptureTraceData;
  openTrace: openTrace.ActionOpenTrace;
}
