/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * Name of the action event (e.g. "retrieve-info")
   */
  name: string;
  /**
   * JSON string for properties of the action event
   */
  properties?: string;
}
