/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The user ID to identify (use {{event.userId}})
   */
  userId?: string;
  /**
   * Name of the user
   */
  name?: string;
  /**
   * Email of the user
   */
  email?: string;
  /**
   * Additional user properties (MUST be a JSON string)
   */
  properties?: {
    [k: string]: any;
  };
}
