/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The message ID to assign the metadata to (use {{workflow.messageId}})
   */
  messageId?: string;
  /**
   * Metadata of the trace data (MUST be a JSON string)
   */
  metadata: string;
}
